language: ruby

install: echo "party time"

script: echo "like it's cat meow 99" && true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: zeratulmdq/awsdeploytest
    bucket: zeratulmdq-awstestdeploy
#  - provider: codedeploy
#    access_key_id: $access_key_id
#    secret_access_key: $secret_access_key
#    bucket: zeratulmdq-awstestdeploy
#    key: latest.zip
#    bundle_type: zip
#    application: jointlynodetest
#    deployment_group: jointlyNodeGroup
#    on: *2